---
# Where to checkout/store Thalassa sources
sources: /mnt/d/Thalassa

# Where to actualy build app
thalassa_path:
    api:    /opt/thalassa/ThalassaApi
    config: /etc/thalassa
    logs:   /var/log/thalassa

# Thalassa Apps user
user: thalassa

# Git settings
git:
    thalassa_repo:  https://github.com/Arrekin/Thalassa.git
    default_branch: master

...